#!/bin/bash
set -o allexport
urllink=$1
su guillaume <<'EOF'
WORKINGDIR=""
serverpath="superpowers/app/server/"
cd
cd "$serverpath"
forever-service delete start.js
cd
sudo rm -r "superpowers"
wget -q $urllink -O "sup"
filename=$(unzip -qql "sup" | head -n1 | tr -s ' ' | cut -d' ' -f5-)
unzip -q "sup"
mv $filename "superpowers"
rm -r "sup"
chmod -R 755 "superpowers"
cd "$serverpath"
forever install start.js
echo "Rebuilt and now running..."
EOF