#!/bin/bash
WORKINGDIR=""
cd "~"
#cd $WORKINGDIR
sudo rm -r "superpowers"
sudo wget -q $1 -O "sup"
filename=$(unzip -qql "sup" | head -n1 | tr -s ' ' | cut -d' ' -f5-)
sudo unzip -q "sup"
sudo mv $filename "superpowers"
sudo rm -r "sup"
sudo chmod -R 777 "superpowers"
cd "superpowers/app/server/"
sudo forever stop start.js
sudo forever start start.js
echo "Running !"
